#!/bin/bash

sudo apt-get update
sudo apt-get  install nginx -y
sudo systemctl start nginx

​​echo "<h1>Server Details</h1><p><strong>Hostname:</strong> $(hostname)</p><p><strong>IP Address:</strong> $(hostname -I | cut -d" " -f1)</p>" > /var/www/html/index.html


sudo systemctl stop nginx
sudo systemctl start nginx
